# 💡 공통 설정 블록: 3개 봇에 공통으로 들어갈 설정을 미리 정의합니다.
x-bot-common: &bot-common
  build: .
  restart: always          # 서버 재시작 시 봇도 자동 재시작
  network_mode: "host"
  env_file: .env
  extra_hosts:
    - "host.docker.internal:host-gateway" # ⭐ 핵심: 도커 안에서 호스트 DB(localhost)로 연결해주는 통로

services:
#  mariadb:
#    image: mariadb:10.11
#    container_name: aegis_db
#    restart: unless-stopped
#    ports:
#      - "3305:3305"
#    env_file: .env   # 💡 .env 파일의 내용을 환경 변수로 주입 
#    environment:
#      #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      #MYSQL_DATABASE: ${DB_NAME}
#      MARIADB_ROOT_PASSWORD: ${DB_PASS}
#      MARIADB_DATABASE: ${DB_NAME}
#      MARIADB_USER: ${DB_USER}
#      MARIADB_PASSWORD: ${DB_PASS}
#      TZ: Asia/Seoul
#    volumes:
#      - ./db_data:/var/lib/mysql

# 🛡️ 1. 코어 엔진 (Core Engine)
  core-bot:
    <<: *bot-common
    container_name: aegis_core_${ACCOUNT_ID}
    profiles: ["core","all"]
#    restart: unless-stopped
#    depends_on:
#      - mariadb
    env_file: .env
    environment:
      - ACCOUNT_ID=${ACCOUNT_ID}
      - ENGINE_TYPE=CORE
      - MAX_BUDGET=${CORE_MAX_BUDGET}
      - TARGET_SLOTS=2
      - TZ=Asia/Seoul

  # 🏹 2. 헌터 엔진 (Hunter Engine)
  hunter-bot:
    <<: *bot-common
    container_name: aegis_hunter_${ACCOUNT_ID}
    profiles: ["hunter","all"]
#    restart: unless-stopped
#    depends_on:
#      - mariadb
    env_file: .env
    environment:
      - ACCOUNT_ID=${ACCOUNT_ID}
      - ENGINE_TYPE=HUNTER
      - MAX_BUDGET=${HUNTER_MAX_BUDGET}
      - TARGET_SLOTS=5
      - TZ=Asia/Seoul

  # 📊 3. 스마트 그리드 엔진 (Smart Grid Engine)
  grid-bot:
    <<: *bot-common
    container_name: aegis_grid_${ACCOUNT_ID}
    profiles: ["grid","all"]
#    restart: unless-stopped
#    depends_on:
#      - mariadb
    env_file: .env
    environment:
      - ACCOUNT_ID=${ACCOUNT_ID}
      - ENGINE_TYPE=GRID
      - MAX_BUDGET=${GRID_MAX_BUDGET}
      - TZ=Asia/Seoul

  # 통합봇    
#  aegis-bot:
#    build: .
#    container_name: aegis_v17_bot
#    restart: unless-stopped
#    depends_on:
#      - mariadb
#    env_file: .env   # 💡 봇 컨테이너에도 환경 변수 주입 
#    environment:
#      - TZ=Asia/Seoul