# 💡 공통 설정 블록: 3개 봇에 공통으로 들어갈 설정을 미리 정의합니다.
x-bot-common: &bot-common
  build: .
  restart: always          # 서버 재시작 시 봇도 자동 재시작
  network_mode: "host"
  env_file: .env
  extra_hosts:
    - "host.docker.internal:host-gateway" # ⭐ 핵심: 도커 안에서 호스트 DB(localhost)로 연결해주는 통로

services:
  coin-bot:
    <<: *bot-common
    container_name: aegis_bot_${ACCOUNT_ID}
    #    restart: unless-stopped
#    depends_on:
#      - mariadb
    env_file: .env
    environment:
      - ACCOUNT_ID=${ACCOUNT_ID}
      - ENGINE_TYPE=GRID
      - MAX_BUDGET=${GRID_MAX_BUDGET}
      - ENABLE_TELEGRAM_COMMANDS=True
      - TZ=Asia/Seoul
    network_mode: "host"      
